Repository TU-ADSP/Blockchain-Logging-Framework, pull requests merged in 2020-12, with the labels that each got.

#40 #35 - implement "connect", "set output folder" commands in grammar
  src/main/antlr4/au/csiro/data61/aap/elf/parsing/Ethql.g4
  src/main/java/au/csiro/data61/aap/elf/ElfApp.java
  src/main/java/au/csiro/data61/aap/elf/Extractor.java
  src/main/java/au/csiro/data61/aap/elf/configuration/EthqlProgramComposer.java
  src/main/java/au/csiro/data61/aap/elf/configuration/MethodSpecification.java
  src/main/java/au/csiro/data61/aap/elf/generation/SolidityCodeGeneration.java
  src/main/java/au/csiro/data61/aap/elf/library/Library.java
  src/main/java/au/csiro/data61/aap/elf/parsing/SemanticAnalysis.java
  src/main/java/au/csiro/data61/aap/elf/util/CompositeEthqlListener.java
  src/main/java/au/csiro/data61/aap/elf/util/CompositeListenerException.java
Labels: enhancement

#44 #43 Add git pre-commit hook and update the readme
  .githooks/pre-commit
  README.md
Labels: documentation

#45 Fix critical sonar code smells and a bug
  src/main/java/au/csiro/data61/aap/elf/core/readers/EthereumTransaction.java
  src/main/java/au/csiro/data61/aap/elf/core/values/BlockVariables.java
  src/main/java/au/csiro/data61/aap/elf/core/values/TransactionVariables.java
  src/main/java/au/csiro/data61/aap/elf/core/writers/AddXesEventInstruction.java
  src/main/java/au/csiro/data61/aap/elf/core/writers/XesWriter.java
  src/main/java/au/csiro/data61/aap/elf/generation/BitMappingItem.java
  src/main/java/au/csiro/data61/aap/elf/generation/ItemGenerator.java
  src/main/java/au/csiro/data61/aap/elf/generation/ValueDictionaryItem.java
  src/main/java/au/csiro/data61/aap/elf/library/Library.java
  src/main/java/au/csiro/data61/aap/elf/parsing/VariableExistenceAnalyzer.java
Labels: bug, refactoring

#51 #32 antlr4 grammar doc
  pom.xml
  src/main/antlr4/au/csiro/data61/aap/elf/parsing/BcQLLexer.g4
  src/main/antlr4/au/csiro/data61/aap/elf/parsing/Ethql.g4
  src/main/antlr4/au/csiro/data61/aap/elf/parsing/Util.g4
  src/main/java/au/csiro/data61/aap/elf/Extractor.java
  src/main/resources/Bockrath_Forsage.ethql
Labels: refactoring

#55 Closes #52 - exception handling in EthereumListener methods
  src/main/java/au/csiro/data61/aap/elf/configuration/EthereumListener.java
Labels: refactoring

#64 Closes #48 - modularize ethereum logging functionality
  src/main/antlr4/au/csiro/data61/aap/elf/parsing/Bcql.g4
  src/main/antlr4/au/csiro/data61/aap/elf/parsing/BcqlLexemes.g4
  src/main/antlr4/au/csiro/data61/aap/elf/parsing/BcqlUtil.g4
  src/main/java/au/csiro/data61/aap/elf/BcqlProcessingException.java
  src/main/java/au/csiro/data61/aap/elf/Constants.java
  src/main/java/au/csiro/data61/aap/elf/ElfApp.java
  src/main/java/au/csiro/data61/aap/elf/Extractor.java
  src/main/java/au/csiro/data61/aap/elf/Generator.java
  src/main/java/au/csiro/data61/aap/elf/Validator.java
  src/main/java/au/csiro/data61/aap/elf/configuration/BaseBlockchainListener.java
  src/main/java/au/csiro/data61/aap/elf/configuration/EthereumListener.java
  src/main/java/au/csiro/data61/aap/elf/configuration/EthqlProgramComposer.java
  src/main/java/au/csiro/data61/aap/elf/generation/BaseGenerator.java
  src/main/java/au/csiro/data61/aap/elf/generation/ItemGenerator.java
  src/main/java/au/csiro/data61/aap/elf/generation/SolidityCodeGeneration.java
  src/main/java/au/csiro/data61/aap/elf/parsing/EmitAnalyzer.java
  src/main/java/au/csiro/data61/aap/elf/parsing/EthqlInterpreter.java
  src/main/java/au/csiro/data61/aap/elf/parsing/ExpressionStatementAnalyzer.java
  src/main/java/au/csiro/data61/aap/elf/parsing/FilterDefinitionAnalyzer.java
  src/main/java/au/csiro/data61/aap/elf/parsing/FilterNestingAnalyzer.java
  src/main/java/au/csiro/data61/aap/elf/parsing/InterpreterUtils.java
  src/main/java/au/csiro/data61/aap/elf/parsing/SemanticAnalysis.java
  src/main/java/au/csiro/data61/aap/elf/parsing/SemanticAnalyzer.java
  src/main/java/au/csiro/data61/aap/elf/parsing/VariableExistenceListener.java
  src/main/java/au/csiro/data61/aap/elf/util/RootListener.java
  src/main/java/au/csiro/data61/aap/elf/util/RootListenerException.java
  src/main/java/au/csiro/data61/aap/samples/ValidatorTest.java
  src/main/resources/Bockrath_Forsage.ethql
  src/test/groovy/au/csiro/data61/aap/elf/configuration/EthereumListenerSpec.groovy
  src/test/java/au/csiro/data61/aap/elf/ValidatorSemanticSpec.java
Labels: refactoring

#65 Closes #62 - modify manifest files to current grammar
  src/main/resources/Augur.ethql
  src/main/resources/AugurContractRegistry.ethql
  src/main/resources/Bockrath_Raiden.ethql
  src/main/resources/CryptoKitties.ethql
  src/main/resources/NetworkStatistics.ethql
  src/main/resources/Rebesky_Augur.ethql
  src/main/resources/Rebesky_ChickenHunt.ethql
  src/main/resources/Rebesky_Idex1.ethql
  src/main/resources/Rebesky_Idex2.ethql
  src/main/resources/Rebesky_Idex3.ethql
Labels: enhancement

#67 Closes #60 - add connection functionality to HyperledgerConnection class
  .gitignore
  pom.xml
  src/main/java/blf/blockchains/hyperledger/HyperledgerListener.java
  src/main/java/blf/blockchains/hyperledger/connection/HyperledgerConnection.java
  src/main/java/blf/blockchains/hyperledger/state/HyperledgerState.java
  src/main/resources/Digtiar_Hyperledger_Test.bcql
Labels: enhancement
