Repository TU-ADSP/Blockchain-Logging-Framework, pull requests merged in 2020-11, with the labels that each got.

#12 Introduce local maven repository to simplify the local jar imports and downgrade to Java 11
  lib/repo/org/deckfour/open-xes/1.0/open-xes-1.0.jar
  lib/repo/org/deckfour/open-xes/1.0/open-xes-1.0.jar.md5
  lib/repo/org/deckfour/open-xes/1.0/open-xes-1.0.jar.sha1
  lib/repo/org/deckfour/open-xes/1.0/open-xes-1.0.pom
  lib/repo/org/deckfour/open-xes/1.0/open-xes-1.0.pom.md5
  lib/repo/org/deckfour/open-xes/1.0/open-xes-1.0.pom.sha1
  lib/repo/org/deckfour/open-xes/maven-metadata.xml
  lib/repo/org/deckfour/open-xes/maven-metadata.xml.md5
  lib/repo/org/deckfour/open-xes/maven-metadata.xml.sha1
  lib/repo/org/deckfour/spex/1.0/spex-1.0.jar
  lib/repo/org/deckfour/spex/1.0/spex-1.0.jar.md5
  lib/repo/org/deckfour/spex/1.0/spex-1.0.jar.sha1
  lib/repo/org/deckfour/spex/1.0/spex-1.0.pom
  lib/repo/org/deckfour/spex/1.0/spex-1.0.pom.md5
  lib/repo/org/deckfour/spex/1.0/spex-1.0.pom.sha1
  lib/repo/org/deckfour/spex/maven-metadata.xml
  lib/repo/org/deckfour/spex/maven-metadata.xml.md5
  lib/repo/org/deckfour/spex/maven-metadata.xml.sha1
  pom.xml
Labels: enhancement

#15 Closes #13 - add Jenkins build status badge
  README.md
Labels: refactoring

#18 Closes #16 - setup GitHub Java CI workflow
  .github/workflows/maven.yml
  README.md
Labels: devops, documentation

#21 Closes #20 - auto-deploy javadoc to github-pages + update docs
  README.md
  pom.xml
  src/main/java/au/csiro/data61/aap/elf/core/filters/LogEntryFilter.java
Labels: devops, documentation

#36 #31 - change default setting to build jar
  README.md
  pom.xml
Labels: refactoring

#38 #33 - change maven name to Blockchain Logging Framework
  pom.xml
Labels: refactoring

#39 #33 - add SonarQube badges to README.md
  README.md
Labels: devops, documentation
