Repository TU-ADSP/Blockchain-Logging-Framework, pull requests merged in 2021-01, with the labels that each got.

#75 Implement initial version of e2e test
  src/test/e2e/run.sh
Labels: enhancement, tests

#84 #83 - refactor e2e bash script and add flags
  .gitignore
  src/test/e2e/bcql/AugurContractRegistry.bcql
  src/test/e2e/bcql/ChickenHunt.bcql
  src/test/e2e/bcql/CryptoKitties.bcql
  src/test/e2e/bcql/NetworkStatistics.bcql
  src/test/e2e/bcql/Rebesky_Augur.bcql
  src/test/e2e/bcql/Rebesky_ChickenHunt.bcql
  src/test/e2e/bcql/Rebesky_Idex1.bcql
  src/test/e2e/outputs/AugurContractRegistry.o
  src/test/e2e/outputs/CryptoKitties.o
  src/test/e2e/outputs/NetworkStatistics.o
  src/test/e2e/outputs/Rebesky_Augur.o
  src/test/e2e/outputs/Rebesky_ChickenHunt.o
  src/test/e2e/outputs/Rebesky_Idex1.o
  src/test/e2e/run.sh
Labels: refactoring

#93 #80 hotfix blocknumber comparison
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerBlockFilterInstruction.java
Labels: bug

#92 #82 hotfix requested eventname for indexing nested json
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerLogEntryFilterInstruction.java
Labels: bug

#94 #82 hotfix address names contain quotes
  src/main/java/blf/blockchains/hyperledger/HyperledgerListener.java
Labels: bug

#96 #95 - publish the test manifest from the meeting
  src/main/resources/HyperBasic.bcql
Labels: enhancement, tests

#107 #99 - test the extraction of structured event data of hyperledger
  src/main/java/blf/blockchains/hyperledger/HyperledgerListener.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerLogEntryFilterInstruction.java
  src/main/resources/CryptoKittiesAsHyper.bcql
  src/main/resources/HyperKitties.bcql
Labels: bug, enhancement, tests

#109 #108 - blf hyperledger does not exit when analyzing until the very last block in the ledger
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerBlockFilterInstruction.java
Labels: bug

#105 #101 - transaction filter template implementation
  src/main/java/blf/blockchains/hyperledger/HyperledgerListener.java
  src/main/java/blf/blockchains/hyperledger/helpers/HyperledgerListenerHelper.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerLogEntryFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerTransactionFilterInstruction.java
  src/main/java/blf/core/instructions/FilterInstruction.java
  src/main/resources/HyperBasic.bcql
Labels: enhancement, refactoring

#114 #113 - kitty id not found in crypto kitties as hyper manifest
  src/main/resources/CryptoKittiesAsHyper.bcql
Labels: bug, tests

#115 #112 - allocate exception handler once
  src/main/java/blf/blockchains/hyperledger/HyperledgerListener.java
  src/main/java/blf/blockchains/hyperledger/helpers/HyperledgerListenerHelper.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerBlockFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerConnectInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerLogEntryFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerTransactionFilterInstruction.java
  src/main/java/blf/configuration/BaseBlockchainListener.java
  src/main/java/blf/core/state/ProgramState.java
Labels: refactoring

#118 #111 - refactor variables system
  src/main/antlr4/blf/grammar/Bcql.g4
  src/main/java/blf/blockchains/ethereum/EthereumListener.java
  src/main/java/blf/blockchains/ethereum/state/EthereumProgramState.java
  src/main/java/blf/blockchains/ethereum/variables/EthereumBlockVariables.java
  src/main/java/blf/blockchains/ethereum/variables/EthereumLogEntryVariables.java
  src/main/java/blf/blockchains/ethereum/variables/EthereumTransactionVariables.java
  src/main/java/blf/blockchains/ethereum/variables/EthereumVariable.java
  src/main/java/blf/blockchains/ethereum/variables/EthereumVariables.java
  src/main/java/blf/blockchains/hyperledger/HyperledgerListener.java
  src/main/java/blf/blockchains/hyperledger/helpers/HyperledgerListenerHelper.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerBlockFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerLogEntryFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerTransactionFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/state/HyperledgerProgramState.java
  src/main/java/blf/blockchains/hyperledger/variables/HyperledgerBlockVariables.java
  src/main/java/blf/blockchains/hyperledger/variables/HyperledgerLogEntryVariables.java
  src/main/java/blf/blockchains/hyperledger/variables/HyperledgerTransactionVariables.java
  src/main/java/blf/blockchains/hyperledger/variables/HyperledgerVariables.java
  src/main/java/blf/configuration/BaseBlockchainListener.java
  src/main/java/blf/configuration/BlockNumberSpecification.java
  src/main/java/blf/configuration/ValueAccessorSpecification.java
  src/main/java/blf/core/state/ProgramState.java
  src/main/java/blf/core/values/BlockchainVariables.java
  src/main/java/blf/core/values/ValueStore.java
  src/main/java/blf/core/values/Variable.java
  src/main/java/blf/core/values/Variables.java
  src/main/java/blf/parsing/EthqlInterpreter.java
  src/main/java/blf/parsing/FilterDefinitionAnalyzer.java
  src/main/java/blf/parsing/SemanticAnalysis.java
  src/main/java/blf/parsing/VariableExistenceListener.java
  src/main/java/blf/util/RootListener.java
  src/main/resources/HyperBasic.bcql
  src/test/groovy/blf/ValidatorSemanticSpec.groovy
Labels: enhancement, refactoring

#125 #27 - rename EthQL to BcQL to coincide with the purpose of the framework
  README.md
  pom.xml
  src/main/java/blf/Generator.java
  src/main/java/blf/Validator.java
  src/main/java/blf/parsing/BcqlInterpreter.java
  src/main/java/blf/samples/SampleUtils.java
  src/main/resources/Augur.bcql
  src/main/resources/AugurContractRegistry.bcql
  src/main/resources/Bockrath_Forsage.bcql
  src/main/resources/Bockrath_Raiden.bcql
  src/main/resources/CryptoKitties.bcql
  src/main/resources/GeneratorGitExample.bcql
  src/main/resources/GeneratorShirtExample.bcql
  src/main/resources/NetworkStatistics.bcql
  src/main/resources/Rebesky_Augur.bcql
  src/main/resources/Rebesky_ChickenHunt.bcql
  src/main/resources/Rebesky_Idex1.bcql
  src/main/resources/Rebesky_Idex2.bcql
  src/main/resources/Rebesky_Idex3.bcql
  src/test/e2e/run.sh
  src/test/groovy/blf/ValidatorSyntaxSpec.groovy
Labels: documentation, enhancement

#121 #41 - any order of connection and outputFolder in the manifest file should be accepted by the grammar
  src/main/antlr4/blf/grammar/Bcql.g4
Labels: enhancement

#135 #131 - remove unused classes in hyperledger
  src/main/java/blf/blockchains/ethereum/classes/EthereumLogEntrySignature.java
  src/main/java/blf/blockchains/ethereum/classes/EthereumPublicMemberQueryEthereum.java
  src/main/java/blf/blockchains/ethereum/classes/EthereumSmartContractParameter.java
  src/main/java/blf/blockchains/ethereum/classes/EthereumSmartContractQuery.java
  src/main/java/blf/blockchains/ethereum/instructions/EthereumLogEntryFilterInstruction.java
  src/main/java/blf/blockchains/ethereum/instructions/EthereumSmartContractFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/reader/HyperledgerBlock.java
  src/main/java/blf/blockchains/hyperledger/reader/HyperledgerClient.java
  src/main/java/blf/blockchains/hyperledger/reader/HyperledgerDataReader.java
  src/main/java/blf/blockchains/hyperledger/reader/HyperledgerLogEntry.java
  src/main/java/blf/blockchains/hyperledger/reader/HyperledgerTransaction.java
  src/main/java/blf/blockchains/hyperledger/state/HyperledgerProgramState.java
  src/main/java/blf/configuration/LogEntrySignatureSpecification.java
  src/main/java/blf/configuration/SmartContractFilterSpecification.java
  src/main/java/blf/configuration/SmartContractQuerySpecification.java
  src/main/java/blf/configuration/SpecificationComposer.java
Labels: refactoring

#137 #136 - fix block.hash and transaction.hash in Hyperledger extraction are not correct
  src/main/java/blf/blockchains/hyperledger/helpers/HyperledgerListenerHelper.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerBlockFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerTransactionFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/variables/HyperledgerBlockVariables.java
  src/main/java/blf/blockchains/hyperledger/variables/HyperledgerTransactionVariables.java
  src/main/resources/HyperBasic.bcql
Labels: bug, high priority

#138 #128 - configure Hyperledger e2e tests
  src/test/e2e/bcql/CryptoKittiesAsHyper.bcql
  src/test/e2e/bcql/HyperBasic.bcql
  src/test/e2e/bcql/HyperKitties.bcql
  src/test/e2e/credentials/connection-org1.yaml
  src/test/e2e/credentials/server.crt
  src/test/e2e/credentials/server.key
  src/test/e2e/outputs/CryptoKittiesAsHyper_log_pid0_all.o
  src/test/e2e/outputs/HyperBasic_all.o
  src/test/e2e/outputs/HyperBasic_log_testEvent_all.o
  src/test/e2e/outputs/HyperBasic_payload_all.o
  src/test/e2e/outputs/HyperKitties_Birth_all.o
  src/test/e2e/outputs/HyperKitties_Pregnant_all.o
  src/test/e2e/outputs/HyperKitties_Transfer_all.o
  src/test/e2e/outputs/HyperKitties_all.o
  src/test/e2e/outputs/HyperKitties_log_Birth_all.o
  src/test/e2e/outputs/HyperKitties_log_Pregnant_all.o
  src/test/e2e/outputs/HyperKitties_log_Transfer_all.o
  src/test/e2e/run.sh
Labels: enhancement, tests

#140 [#130, #134] - merge FilterInstruction to Instruction and rename HyperledgerListenerHelper to HyperledgerInstructionHelper
  src/main/java/blf/blockchains/ethereum/instructions/EthereumBlockFilterInstruction.java
  src/main/java/blf/blockchains/ethereum/instructions/EthereumConnectInstruction.java
  src/main/java/blf/blockchains/ethereum/instructions/EthereumConnectIpcInstruction.java
  src/main/java/blf/blockchains/ethereum/instructions/EthereumLogEntryFilterInstruction.java
  src/main/java/blf/blockchains/ethereum/instructions/EthereumSmartContractFilterInstruction.java
  src/main/java/blf/blockchains/ethereum/instructions/EthereumTransactionFilterInstruction.java
  src/main/java/blf/blockchains/ethereum/reader/EthereumDataReader.java
  src/main/java/blf/blockchains/hyperledger/HyperledgerListener.java
  src/main/java/blf/blockchains/hyperledger/helpers/HyperledgerInstructionHelper.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerBlockFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerConnectInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerLogEntryFilterInstruction.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerTransactionFilterInstruction.java
  src/main/java/blf/configuration/InstructionSpecification.java
  src/main/java/blf/configuration/SpecificationComposer.java
  src/main/java/blf/core/Program.java
  src/main/java/blf/core/instructions/AddCsvRowInstruction.java
  src/main/java/blf/core/instructions/AddLogLineInstruction.java
  src/main/java/blf/core/instructions/AddXesElementInstruction.java
  src/main/java/blf/core/instructions/FilterInstruction.java
  src/main/java/blf/core/instructions/GenericFilterInstruction.java
  src/main/java/blf/core/instructions/Instruction.java
  src/main/java/blf/core/instructions/MethodCallInstruction.java
  src/main/java/blf/core/instructions/SetOutputFolderInstruction.java
  src/main/java/blf/core/instructions/VariableAssignmentInstruction.java
  src/main/java/blf/core/interfaces/Instruction.java
Labels: refactoring

#139 #127 - check if there exist meaningful hyperledger log entry variables
  src/main/java/blf/blockchains/hyperledger/variables/HyperledgerLogEntryVariables.java
  src/main/java/blf/blockchains/hyperledger/variables/HyperledgerVariables.java
Labels: refactoring

#144 #142 - add comand line flag to abort on error
  src/main/java/blf/BlfApp.java
  src/main/java/blf/Extractor.java
  src/main/java/blf/core/exceptions/ExceptionHandler.java
  src/main/java/blf/samples/ExtractorTest.java
  src/main/resources/FailingHyperKitties.bcql
  src/test/e2e/bcql/FailingCryptoKitties.bcql
  src/test/e2e/bcql/FailingHyperKitties.bcql
  src/test/e2e/run.sh
Labels: enhancement

#146 #145 - fix Java version in Readme
  README.md
Labels: documentation

#155 #126 - make manifest setup rules mandatory (includes test adaptations)
  src/main/antlr4/blf/grammar/Bcql.g4
  src/test/java/blf/ValidatorSyntaxTest.java
  src/test/resources/ValidatorSemanticTestGenericData.yaml
  src/test/resources/ValidatorSemanticTestLogEntryData.yaml
  src/test/resources/ValidatorSemanticTestTransactionData.yaml
Labels: enhancement

#154 #68 - refactor groovy tests into appropriate junit tests
  pom.xml
  src/main/antlr4/blf/grammar/Bcql.g4
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerTransactionFilterInstruction.java
  src/test/groovy/blf/ValidatorSemanticSpec.groovy
  src/test/groovy/blf/ValidatorSyntaxSpec.groovy
  src/test/groovy/blf/configuration/EthereumListenerSpec.groovy
  src/test/groovy/blf/configuration/GenericFilterPredicateSpecificationSpec.groovy
  src/test/groovy/blf/configuration/SpecificationComposerSpec.groovy
  src/test/java/blf/ValidatorSemanticTest.java
  src/test/java/blf/ValidatorSyntaxTest.java
  src/test/java/blf/YamlTestLoader.java
  src/test/java/blf/configuration/GenericFilterPredicateSpecificationTest.java
  src/test/java/blf/configuration/SpecificationComposerTest.java
  src/test/java/blf/validator-test-items.md
  src/test/resources/ValidatorSemanticTestGenericData.yaml
  src/test/resources/ValidatorSemanticTestLogEntryData.yaml
  src/test/resources/ValidatorSemanticTestTransactionData.yaml
Labels: enhancement

#153 #132 - hyperledger smart contract filter template implementation
  src/main/antlr4/blf/grammar/BcqlUtil.g4
  src/main/java/blf/blockchains/hyperledger/HyperledgerListener.java
  src/main/java/blf/blockchains/hyperledger/helpers/HyperledgerInstructionHelper.java
  src/main/java/blf/blockchains/hyperledger/helpers/HyperledgerQueryParameters.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerSmartContractFilterInstruction.java
  src/main/java/blf/parsing/FilterDefinitionAnalyzer.java
  src/main/resources/HyperContract.bcql
Labels: enhancement

#156 #68 - hotfix pom file dependency collision
  pom.xml
Labels: bug
