Repository TU-ADSP/Blockchain-Logging-Framework, pull requests merged in 2021-02, with the labels that each got.

#159 #149 - add emission mode to grammar
  src/main/java/blf/configuration/BaseBlockchainListener.java
  src/main/java/blf/configuration/EmissionSettings.java
  src/main/java/blf/core/state/ProgramState.java
Labels: enhancement

#160 [#150, #151] - implement safe batching and streaming emission modes
  src/main/java/blf/blockchains/ethereum/instructions/EthereumBlockFilterInstruction.java
  src/main/java/blf/blockchains/ethereum/variables/EthereumVariables.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerBlockFilterInstruction.java
  src/main/java/blf/core/instructions/BlockInstruction.java
  src/main/java/blf/core/state/ProgramState.java
  src/main/java/blf/core/writers/CsvWriter.java
  src/main/java/blf/core/writers/DataWriter.java
  src/main/java/blf/core/writers/DataWriters.java
  src/main/java/blf/core/writers/LogWriter.java
  src/main/java/blf/core/writers/XesWriter.java
Labels: enhancement

#162 #161 - add e2e tests for streaming and safe batching modes
  src/test/e2e/bcql/AugurContractRegistryStreaming.bcql
  src/test/e2e/bcql/CryptoKittiesStreaming.bcql
  src/test/e2e/bcql/HyperBasicStreaming.bcql
  src/test/e2e/bcql/NetworkStatisticsStreaming.bcql
  src/test/e2e/outputs/AugurContractRegistry/all.log.xelf
  src/test/e2e/outputs/AugurContractRegistryStreaming/5926257.log.xblf
  src/test/e2e/outputs/AugurContractRegistryStreaming/5926270.log.xblf
  src/test/e2e/outputs/AugurContractRegistryStreaming/5926285.log.xblf
  src/test/e2e/outputs/CryptoKitties/log_pid0_all.xes.xelf
  src/test/e2e/outputs/CryptoKittiesAsHyper/log_pid0_all.xes.xblf
  src/test/e2e/outputs/CryptoKittiesStreaming/log_pid0_6605100.xes.xblf
  src/test/e2e/outputs/CryptoKittiesStreaming/log_pid0_6605106.xes.xblf
  src/test/e2e/outputs/CryptoKittiesStreaming/log_pid0_6605107.xes.xblf
  src/test/e2e/outputs/HyperBasic/all.log.xblf
  src/test/e2e/outputs/HyperBasic/log_testEvent_all.xes.xblf
  src/test/e2e/outputs/HyperBasic/payload_all.csv.xblf
  src/test/e2e/outputs/HyperBasicStreaming/30.log.xblf
  src/test/e2e/outputs/HyperBasicStreaming/31.log.xblf
  src/test/e2e/outputs/HyperBasicStreaming/32.log.xblf
  src/test/e2e/outputs/HyperBasicStreaming/33.log.xblf
  src/test/e2e/outputs/HyperKitties/Birth_all.csv.xblf
  src/test/e2e/outputs/HyperKitties/Pregnant_all.csv.xblf
  src/test/e2e/outputs/HyperKitties/Transfer_all.csv.xblf
  src/test/e2e/outputs/HyperKitties/all.log.xblf
  src/test/e2e/outputs/HyperKitties/log_Birth_all.xes.xblf
  src/test/e2e/outputs/HyperKitties/log_Pregnant_all.xes.xblf
  src/test/e2e/outputs/HyperKitties/log_Transfer_all.xes.xblf
  src/test/e2e/outputs/NetworkStatistics/NetworkStatistics_all.csv.xelf
  src/test/e2e/outputs/NetworkStatisticsStreaming/NetworkStatistics_6000000.csv.xblf
  src/test/e2e/outputs/NetworkStatisticsStreaming/NetworkStatistics_6000001.csv.xblf
  src/test/e2e/outputs/NetworkStatisticsStreaming/NetworkStatistics_6000002.csv.xblf
  src/test/e2e/outputs/NetworkStatisticsStreaming/NetworkStatistics_6000003.csv.xblf
  src/test/e2e/outputs/Rebesky_Augur/log_pid0_all.xes.xelf
  src/test/e2e/outputs/Rebesky_ChickenHunt/log_pid0_all.xes.xelf
  src/test/e2e/outputs/Rebesky_Idex1/Idex_calls_all.csv.xelf
  src/test/e2e/run.sh
Labels: enhancement, tests

#168 #152 - add support for CURRENT keyword hyperledger block filter
  src/main/java/blf/blockchains/hyperledger/helpers/HyperledgerInstructionHelper.java
  src/main/java/blf/blockchains/hyperledger/instructions/HyperledgerBlockFilterInstruction.java
Labels: enhancement

#170 #169 - hotfix SnakeYaml dependency scope
  pom.xml
Labels: bug

#173 [#124, #129] - add useful transformation capabilities, a test file and a wiki page
  src/main/java/blf/library/Library.java
  src/main/java/blf/library/types/ListOperations.java
  src/main/java/blf/library/types/StringOperations.java
  src/main/java/blf/library/util/ReaderOperations.java
  src/main/java/blf/library/util/TriFunction.java
  src/main/resources/TransformationCapabilities.bcql
  src/test/e2e/bcql/TransformationCapabilities.bcql
  src/test/e2e/outputs/TransformationCapabilities/all.log.xblf
  src/test/e2e/run.sh
Labels: documentation, enhancement, refactoring

#174 #172 - mandatory semicolons
  src/main/antlr4/blf/grammar/Bcql.g4
  src/main/resources/AbortOnExceptionTest.bcql
  src/main/resources/Augur.bcql
  src/main/resources/AugurContractRegistry.bcql
  src/main/resources/Bockrath_Forsage.bcql
  src/main/resources/Bockrath_Raiden.bcql
  src/main/resources/CryptoKitties.bcql
  src/main/resources/CryptoKittiesAsHyper.bcql
  src/main/resources/Digtiar_Hyperledger_Test.bcql
  src/main/resources/FailingHyperKitties.bcql
  src/main/resources/HyperBasic.bcql
  src/main/resources/HyperContract.bcql
  src/main/resources/HyperKitties.bcql
  src/main/resources/NetworkStatistics.bcql
  src/main/resources/Rebesky_Augur.bcql
  src/main/resources/Rebesky_ChickenHunt.bcql
  src/main/resources/Rebesky_Idex1.bcql
  src/main/resources/Rebesky_Idex2.bcql
  src/main/resources/Rebesky_Idex3.bcql
  src/main/resources/TransformationCapabilities.bcql
  src/test/e2e/bcql/AugurContractRegistry.bcql
  src/test/e2e/bcql/AugurContractRegistryStreaming.bcql
  src/test/e2e/bcql/ChickenHunt.bcql
  src/test/e2e/bcql/CryptoKitties.bcql
  src/test/e2e/bcql/CryptoKittiesAsHyper.bcql
  src/test/e2e/bcql/CryptoKittiesStreaming.bcql
  src/test/e2e/bcql/FailingCryptoKitties.bcql
  src/test/e2e/bcql/FailingHyperKitties.bcql
  src/test/e2e/bcql/HyperBasic.bcql
  src/test/e2e/bcql/HyperBasicStreaming.bcql
  src/test/e2e/bcql/HyperKitties.bcql
  src/test/e2e/bcql/NetworkStatistics.bcql
  src/test/e2e/bcql/NetworkStatisticsErrorFolder.bcql
  src/test/e2e/bcql/NetworkStatisticsErrorFolderAndName.bcql
  src/test/e2e/bcql/NetworkStatisticsStreaming.bcql
  src/test/e2e/bcql/Rebesky_Augur.bcql
  src/test/e2e/bcql/Rebesky_ChickenHunt.bcql
  src/test/e2e/bcql/Rebesky_Idex1.bcql
  src/test/e2e/bcql/TransformationCapabilities.bcql
  src/test/e2e/run.sh
  src/test/java/blf/ValidatorSyntaxTest.java
  src/test/resources/ValidatorSemanticTestGenericData.yaml
  src/test/resources/ValidatorSemanticTestLogEntryData.yaml
  src/test/resources/ValidatorSemanticTestTransactionData.yaml
Labels: enhancement
